chatgpt:
  token: sk-xxxxxxxxxxxxxxxxxxxx #必填
#  proxy-host: 127.0.0.1 #需要代理时必填
#  proxy-port: 7890 #需要代理时必填
#  model: text-davinci-003 #可选
#  chat-model: gpt-3.5-turbo #可选
#  retries: 10 #可选，默认为5
#  session-expiration-time: 30 #可选，不填则会话永不过期
#  base-url: https://apps.ichati.cn/0a7699ac-bc73-4732-9263-55c1c01f56e3/ #可选，默认为https://api.openai.com/，请记住务必以/结尾
